title: Researcher
url: "https://ankitsultana.com"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/bk2dcradle"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass
