title: Suiyun Zhang
url: "https://zhsuiy.github.io/"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/zhsuiy"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass
